services:

  twitter_db:
    container_name: ${POSTGRES_DB}
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./${POSTGRES_DB}/:/var/lib/postgresql/data

  twitter_app:
    container_name: twitter_app
    build:
      context: twitter_clone
    stop_signal: SIGKILL
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - DEMO_MODE=${DEMO_MODE}
    ports:
      - "${FASTAPI_PORT}:80"
    volumes:
      - ./twitter_logs/:/twitter_clone/logs
      - ./${POSTGRES_DB}/medias/:/twitter_clone/static/images
    depends_on:
      - twitter_db
