services:

  twitter_db:
    container_name: ${POSTGRES_DB}
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./${POSTGRES_DB}/:/var/lib/postgresql/data
    networks:
      - twitter_net

  twitter_app:
    container_name: twitter_app
    build:
      context: twitter_clone
    stop_signal: SIGKILL
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=twitter_db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - DEMO_MODE=${DEMO_MODE}
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    volumes:
      - ./twitter_logs/:/twitter_clone/logs
      - ./${POSTGRES_DB}/medias/:/twitter_clone/static/images
    depends_on:
      - twitter_db
    networks:
      - twitter_net

networks:
  twitter_net:
    name: twitter_net
    driver: bridge